name: user-story-toolkit
title: user-story-toolkit
org: Derrick Ampy
author: Derrick Ampy
author_url: https://github.com/dsampy
base_url: ''
ctx_path: ''
interpolate: false 
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    sitename: user-story-toolkit
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
profiles:
  development:
    deploy: nil 
  production:
    base_url: http://dsampy.github.io/user-story-toolkit-site
    ctx_path: /user-story-toolkit-site
    asciidoctor:
      :attributes:
        base_url: http://dsampy.github.io/user-story-toolkit-site
        ctx_path: /user-story-toolkit-site
        imagesdir: http://dsampy.github.io/user-story-toolkit-site/images 
    deploy:
      host: github_pages
      branch: gh-pages
